/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./code.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "outline-variant": "#c3c6d2",
        "tertiary-container": "#946d00",
        "tertiary": "#755600",
        "on-surface": "#1c1b1b",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#d7e2ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54617d",
        "inverse-primary": "#acc7ff",
        "on-primary-fixed-variant": "#1a4586",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0edec",
        "secondary-fixed-dim": "#b9c6e6",
        "surface-container-high": "#ebe7e7",
        "surface-variant": "#e5e2e1",
        "on-error-container": "#93000a",
        "secondary": "#525e7a",
        "error-container": "#ffdad6",
        "primary-container": "#134A9A",
        "surface-container-highest": "#e5e2e1",
        "on-primary": "#ffffff",
        "secondary-container": "#d0ddfe",
        "primary-fixed-dim": "#acc7ff",
        "surface-dim": "#dcd9d9",
        "secondary-fixed": "#d7e2ff",
        "outline": "#737781",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#261900",
        "primary": "#185FC6",
        "tertiary-fixed": "#ffdea1",
        "success": "#2AA527",
        "on-tertiary-fixed-variant": "#5c4300",
        "surface": "#fcf9f8",
        "on-tertiary-container": "#fffaf7",
        "surface-tint": "#185FC6",
        "on-primary-fixed": "#001a40",
        "on-secondary-fixed-variant": "#3a4761",
        "on-primary-container": "#fcfaff",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#D4AF37",
        "background": "#FFFFFF",
        "surface-muted": "#F4F4F4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0d1b33",
        "on-surface-variant": "#434750",
        "surface-container-low": "#f6f3f2",
        "interactive-black": "#185FC6",
        "secondary-text": "#6E6E73",
        "surface-background": "#F7F8FA",
        "surface-subtle": "#F4F7FB",
        "border-subtle": "#E3EAF4",
      },
      borderRadius: {
        DEFAULT: "6px",
        lg: "10px",
        xl: "14px",
        full: "18px",
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "margin-tablet": "32px",
        "margin-desktop": "64px",
        "container-max": "1200px",
        "section-padding": "80px",
      },
      fontFamily: {
        "display-lg": ["Google Sans Flex", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Google Sans Flex", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Google Sans Flex", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Google Sans Flex", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Google Sans Flex", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.05", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      // Depth instead of hairlines, tinted to the brand hue rather than black,
      // matching the public site's --sh-1 / --sh-2 / --sh-header.
      boxShadow: {
        card: "0 0 0 1px rgba(14,52,104,.05), 0 1px 2px -1px rgba(14,52,104,.07), 0 4px 10px -3px rgba(14,52,104,.05)",
        "card-hover": "0 0 0 1px rgba(14,52,104,.07), 0 2px 5px -2px rgba(14,52,104,.10), 0 14px 30px -8px rgba(14,52,104,.13)",
        header: "0 1px 0 rgba(14,52,104,.05), 0 6px 20px -8px rgba(14,52,104,.14)",
        soft: "0 4px 20px rgba(14,52,104,.06)",
        "soft-lg": "0 8px 32px rgba(28, 25, 23, 0.07)",
      },
      transitionTimingFunction: {
        editorial: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      },
    },
  },
  plugins: [],
};
